name: Flutter CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Se descarga el repo
      - name: Checkout code
        uses: actions/checkout@v3
      # 2. Configurar Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
      # 3. Instalar dependencias de flutter
      - name: Install dependencies
        run: flutter pub get
      # 4. Ejecutar build_runner si hay tests (Por si no hay test por verficicar)
      - name: Run build_runner (if tests exist)
        run: |
          if [ -d "test" ]; then
            echo "Generando archivos con build_runner...";
           dart run build_runner build --delete-conflicting-outputs;
          else
            echo "No hay tests, omitiendo build_runner.";
          fi
      # 5. Verificar si existen pruebas antes de ejecutarlas
      - name: Check if test directory exists
        run: |
          if [ -d "test" ]; then
            echo "Aplicando pruebas...";
            flutter test;
          else
            echo "No existe testeo aun.";
          fi
