# .github/workflows/tipopago-ci.yml
name: TipoPago CI
on: 
  push:
    branches: [ dev-qa, main ]
  pull_request:
    branches: [ dev-qa ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Se descarga el repo
      - name: Checkout code
        uses: actions/checkout@v3
        
      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install
        
      # 4. Verificar si existen pruebas de integración antes de ejecutarlas
      - name: Check if integration tests exist
        run: |
          if [ -d "tests/integration" ]; then
            echo "Ejecutando pruebas de integración de TipoPago...";
            npm run test:integration;
          else
            echo "No existen pruebas de integración aún.";
            echo "Creando estructura de pruebas...";
            mkdir -p tests/integration;
            echo "Estructura creada. Agrega tus pruebas de integración.";
          fi
          
      # 5. Construir aplicación si las pruebas pasan
      - name: Build application
        run: |
          echo "Construyendo aplicación...";
          npm run build;
          
      # 6. Desplegar si es rama DEV-QA y pruebas pasan
      - name: Deploy to staging (DEV-QA branch)
        if: github.ref == 'refs/heads/dev-qa' && success()
        run: |
          echo "🚀 Desplegando a staging desde rama DEV-QA...";
          echo "Todas las pruebas de TipoPago pasaron - Listo para staging";
          
      # 7. Notificar resultado final
      - name: Test results
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Todas las pruebas de integración de TipoPago pasaron correctamente";
            echo "✅ Módulo TipoPago listo para producción";
          else
            echo "❌ Algunas pruebas de integración fallaron";
            echo "❌ Revisar módulo TipoPago antes de continuar";
            exit 1;
          fi
